<?php

use Illuminate\Database\Seeder;

class PRKSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $parent = [
            [
                'id' => 1,
                'desc_prk_parent' => 'Har_Operasi',
                'identity_prk_parent' => '2G',
                'identity_prk_parent_ppa' => '2G',
                'identity_prk_parent_jom' => '3G',
                'identity_prk_parent_usaha_lain' => '', 
                'name_prk_parent' => 'Operasi Unit Pembangkitan',
            ],            
            [
                'id' => 2,
                'desc_prk_parent' => 'Har_Kimia_dan_Laboratorium',
                'identity_prk_parent' => '2H',
                'identity_prk_parent_ppa' => '2H',
                'identity_prk_parent_jom' => '3H',
                'identity_prk_parent_usaha_lain' => '', 
                'name_prk_parent' => 'Kimia & Laboratorium ',
            ],
            [
                'id' => 3,
                'desc_prk_parent' => 'Har_K3',
                'identity_prk_parent' => '2I',
                'identity_prk_parent_ppa' => '2I',
                'identity_prk_parent_jom' => '3I',
                'identity_prk_parent_usaha_lain' => '', 
                'name_prk_parent' => 'K3',
            ],
            [
                'id' => 4,
                'desc_prk_parent' => 'Har_Lingkungan',
                'identity_prk_parent' => '2J',
                'identity_prk_parent_ppa' => '2J',
                'identity_prk_parent_jom' => '3J',
                'identity_prk_parent_usaha_lain' => '', 
                'name_prk_parent' => 'Lingkungan',
            ], 
            [
                'id' => 5,
                'desc_prk_parent' => 'Har_Preventive',
                'identity_prk_parent' => '2K',
                'identity_prk_parent_ppa' => '2K',
                'identity_prk_parent_jom' => '3K',
                'identity_prk_parent_usaha_lain' => '', 
                'name_prk_parent' => 'Preventive Maintenance',
            ],
            [
                'id' => 6,
                'desc_prk_parent' => 'Har_Predictive',
                'identity_prk_parent' => '2L',
                'identity_prk_parent_ppa' => '2L',
                'identity_prk_parent_jom' => '3L',
                'identity_prk_parent_usaha_lain' => '', 
                'name_prk_parent' => 'Predictive Maintenance',
            ],
            [
                'id' => 7,
                'desc_prk_parent' => 'Har_Corrective',
                'identity_prk_parent' => '2M',
                'identity_prk_parent_ppa' => '2M',
                'identity_prk_parent_jom' => '3M',
                'identity_prk_parent_usaha_lain' => '', 
                'name_prk_parent' => 'Corective Maintenance',
            ],
            [
                'id' => 8,
                'desc_prk_parent' => 'Har_Overhaul',
                'identity_prk_parent' => '2N',
                'identity_prk_parent_ppa' => '2N',
                'identity_prk_parent_jom' => '3N',
                'identity_prk_parent_usaha_lain' => '', 
                'name_prk_parent' => 'Overhoul/Inspection',
            ],
            [
                'id' => 9,
                'desc_prk_parent' => 'Har_Project',
                'identity_prk_parent' => '2O',
                'identity_prk_parent_ppa' => '2O',
                'identity_prk_parent_jom' => '3O',
                'identity_prk_parent_usaha_lain' => '', 
                'name_prk_parent' => 'Engineering/Project/Modifikasi',
            ],
            [
                'id' => 10,
                'desc_prk_parent' => 'Har_Non_Instalasi',
                'identity_prk_parent' => '2P',
                'identity_prk_parent_ppa' => '2P',
                'identity_prk_parent_jom' => '3P',
                'identity_prk_parent_usaha_lain' => '', 
                'name_prk_parent' => 'Non Instalasi/ TU/Sarana ',
            ],
            [ 'id' => 11, 'desc_prk_parent'=> 'Pendapatan TL komponen A', 'identity_prk_parent'=> '1A', 'identity_prk_parent_ppa'=> '1A', 'identity_prk_parent_jom'=> '', 'identity_prk_parent_usaha_lain'=> '', 'name_prk_parent'=> 'Pendapatan TL komponen A'],
            [ 'id' => 12, 'desc_prk_parent'=> 'Pendapatan TL komponen B', 'identity_prk_parent'=> '1B', 'identity_prk_parent_ppa'=> '1B', 'identity_prk_parent_jom'=> '', 'identity_prk_parent_usaha_lain'=> '', 'name_prk_parent'=> 'Pendapatan TL komponen B'],
            [ 'id' => 13, 'desc_prk_parent'=> 'Pendapatan TL komponen C', 'identity_prk_parent'=> '1C', 'identity_prk_parent_ppa'=> '1C', 'identity_prk_parent_jom'=> '', 'identity_prk_parent_usaha_lain'=> '', 'name_prk_parent'=> 'Pendapatan TL komponen C'],
            [ 'id' => 14, 'desc_prk_parent'=> 'Pendapatan TL komponen D', 'identity_prk_parent'=> '1D', 'identity_prk_parent_ppa'=> '1D', 'identity_prk_parent_jom'=> '', 'identity_prk_parent_usaha_lain'=> '', 'name_prk_parent'=> 'Pendapatan TL komponen D'],
            [ 'id' => 15, 'desc_prk_parent'=> 'Pendapatan Ancillary Service', 'identity_prk_parent'=> '1E', 'identity_prk_parent_ppa'=> '1E', 'identity_prk_parent_jom'=> '', 'identity_prk_parent_usaha_lain'=> '', 'name_prk_parent'=> 'Pendapatan Ancillary Service'],
            [ 'id' => 16, 'desc_prk_parent'=> 'Pendapatan JOM Fix', 'identity_prk_parent'=> '1F', 'identity_prk_parent_ppa'=> '', 'identity_prk_parent_jom'=> '1F', 'identity_prk_parent_usaha_lain'=> '', 'name_prk_parent'=> 'Pendapatan JOM Fix'],
            [ 'id' => 17, 'desc_prk_parent'=> 'Pendapatan JOM Reimburse', 'identity_prk_parent'=> '1G', 'identity_prk_parent_ppa'=> '', 'identity_prk_parent_jom'=> '1G', 'identity_prk_parent_usaha_lain'=> '', 'name_prk_parent'=> 'Pendapatan JOM Reimburse'],
            [ 'id' => 18, 'desc_prk_parent'=> 'Pendapatan EPC', 'identity_prk_parent'=> '1H', 'identity_prk_parent_ppa'=> '', 'identity_prk_parent_jom'=> '', 'identity_prk_parent_usaha_lain'=> '1H', 'name_prk_parent'=> 'Pendapatan EPC'],
            [ 'id' => 19, 'desc_prk_parent'=> 'Pendapatan usaha lain', 'identity_prk_parent'=> '1I', 'identity_prk_parent_ppa'=> '', 'identity_prk_parent_jom'=> '', 'identity_prk_parent_usaha_lain'=> '1I', 'name_prk_parent'=> 'Pendapatan usaha lain'],
            [ 'id' => 20, 'desc_prk_parent'=> 'Pendapatan di luar usaha - Common', 'identity_prk_parent'=> '1L', 'identity_prk_parent_ppa'=> '1L', 'identity_prk_parent_jom'=> '1L', 'identity_prk_parent_usaha_lain'=> '', 'name_prk_parent'=> 'Pendapatan di luar usaha - Common'],
            [ 'id' => 21, 'desc_prk_parent'=> 'Biaya bahan bakar - Minyak', 'identity_prk_parent'=> '2A', 'identity_prk_parent_ppa'=> '2A', 'identity_prk_parent_jom'=> '3A', 'identity_prk_parent_usaha_lain'=> '', 'name_prk_parent'=> 'Biaya bahan bakar - Minyak'],
            [ 'id' => 22, 'desc_prk_parent'=> 'Biaya bahan bakar - Gas alam', 'identity_prk_parent'=> '2B', 'identity_prk_parent_ppa'=> '2B', 'identity_prk_parent_jom'=> '3B', 'identity_prk_parent_usaha_lain'=> '', 'name_prk_parent'=> 'Biaya bahan bakar - Gas alam'],
            [ 'id' => 23, 'desc_prk_parent'=> 'Biaya bahan bakar - Batubara', 'identity_prk_parent'=> '2C', 'identity_prk_parent_ppa'=> '2C', 'identity_prk_parent_jom'=> '3C', 'identity_prk_parent_usaha_lain'=> '', 'name_prk_parent'=> 'Biaya bahan bakar - Batubara'],
            [ 'id' => 24, 'desc_prk_parent'=> 'Biaya bahan bakar - Minyak pelumas', 'identity_prk_parent'=> '2D', 'identity_prk_parent_ppa'=> '2D', 'identity_prk_parent_jom'=> '3D', 'identity_prk_parent_usaha_lain'=> '', 'name_prk_parent'=> 'Biaya bahan bakar - Minyak pelumas'],
            [ 'id' => 25, 'desc_prk_parent'=> 'Biaya bahan bakar - Kimia', 'identity_prk_parent'=> '2E', 'identity_prk_parent_ppa'=> '2E', 'identity_prk_parent_jom'=> '3E', 'identity_prk_parent_usaha_lain'=> '', 'name_prk_parent'=> 'Biaya bahan bakar - Kimia'],
            [ 'id' => 26, 'desc_prk_parent'=> 'Biaya bahan bakar - AIR', 'identity_prk_parent'=> '2F', 'identity_prk_parent_ppa'=> '2F', 'identity_prk_parent_jom'=> '3F', 'identity_prk_parent_usaha_lain'=> '', 'name_prk_parent'=> 'Biaya bahan bakar - AIR'],
            [ 'id' => 27, 'desc_prk_parent'=> 'Biaya kepegawaian', 'identity_prk_parent'=> '2Q', 'identity_prk_parent_ppa'=> '2Q', 'identity_prk_parent_jom'=> '3Q', 'identity_prk_parent_usaha_lain'=> '', 'name_prk_parent'=> 'Biaya kepegawaian'],
            [ 'id' => 28, 'desc_prk_parent'=> 'Biaya EPC', 'identity_prk_parent'=> '2R', 'identity_prk_parent_ppa'=> '', 'identity_prk_parent_jom'=> '', 'identity_prk_parent_usaha_lain'=> '2R', 'name_prk_parent'=> 'Biaya EPC'],
            [ 'id' => 29, 'desc_prk_parent'=> 'Biaya Penyusutan ', 'identity_prk_parent'=> '2T', 'identity_prk_parent_ppa'=> '2T', 'identity_prk_parent_jom'=> '3T', 'identity_prk_parent_usaha_lain'=> '', 'name_prk_parent'=> 'Biaya Penyusutan '],
            [ 'id' => 30, 'desc_prk_parent'=> 'Biaya di Usaha Lain', 'identity_prk_parent'=> '2U', 'identity_prk_parent_ppa'=> '', 'identity_prk_parent_jom'=> '', 'identity_prk_parent_usaha_lain'=> '2U', 'name_prk_parent'=> 'Biaya di Usaha Lain'],
            [ 'id' => 31, 'desc_prk_parent'=> 'Biaya di luar usaha - Common', 'identity_prk_parent'=> '2V', 'identity_prk_parent_ppa'=> '2V', 'identity_prk_parent_jom'=> '3V', 'identity_prk_parent_usaha_lain'=> '', 'name_prk_parent'=> 'Biaya di luar usaha - Common'],
            [ 'id' => 32, 'desc_prk_parent'=> 'Biaya Reimbursable', 'identity_prk_parent'=> '3Y', 'identity_prk_parent_ppa'=> '', 'identity_prk_parent_jom'=> '3Y', 'identity_prk_parent_usaha_lain'=> '', 'name_prk_parent'=> 'Biaya Reimbursable'],
            [ 'id' => 33, 'desc_prk_parent'=> 'Joint Procurement antar PRK', 'identity_prk_parent'=> '2Z', 'identity_prk_parent_ppa'=> '2Z', 'identity_prk_parent_jom'=> '3Z', 'identity_prk_parent_usaha_lain'=> '', 'name_prk_parent'=> 'Joint Procurement antar PRK'],
            [ 'id' => 34, 'desc_prk_parent'=> 'Investasi Pembangkitan', 'identity_prk_parent'=> '4A', 'identity_prk_parent_ppa'=> '4A', 'identity_prk_parent_jom'=> '4A', 'identity_prk_parent_usaha_lain'=> '', 'name_prk_parent'=> 'Investasi Pembangkitan'],
            [ 'id' => 35, 'desc_prk_parent'=> 'Investasi Pengembangan Usaha', 'identity_prk_parent'=> '4B', 'identity_prk_parent_ppa'=> '', 'identity_prk_parent_jom'=> '', 'identity_prk_parent_usaha_lain'=> '4B', 'name_prk_parent'=> 'Investasi Pengembangan Usaha'],
            [ 'id' => 36, 'desc_prk_parent'=> 'Biaya Administrasi', 'identity_prk_parent'=> '2S', 'identity_prk_parent_ppa'=> '2S', 'identity_prk_parent_jom'=> '3S', 'identity_prk_parent_usaha_lain'=> '', 'name_prk_parent'=> 'Biaya Administrasi'],
        ];

        $inti = [
                    [ 'id' => 1, 'desc_prk_inti'=> 'Common', 'identity_prk_inti'=> '00', 'prk_parent_id'=> 11],
                    [ 'id' => 2, 'desc_prk_inti'=> 'Common', 'identity_prk_inti'=> '00', 'prk_parent_id'=> 12],
                    [ 'id' => 3, 'desc_prk_inti'=> 'Common', 'identity_prk_inti'=> '00', 'prk_parent_id'=> 13],
                    [ 'id' => 4, 'desc_prk_inti'=> 'Common', 'identity_prk_inti'=> '00', 'prk_parent_id'=> 14],
                    [ 'id' => 5, 'desc_prk_inti'=> 'Common', 'identity_prk_inti'=> '00', 'prk_parent_id'=> 15],
                    [ 'id' => 6, 'desc_prk_inti'=> 'Common', 'identity_prk_inti'=> '00', 'prk_parent_id'=> 16],
                    [ 'id' => 7, 'desc_prk_inti'=> 'Common', 'identity_prk_inti'=> '00', 'prk_parent_id'=> 17],
                    [ 'id' => 8, 'desc_prk_inti'=> 'Common', 'identity_prk_inti'=> '00', 'prk_parent_id'=> 18],
                    [ 'id' => 9, 'desc_prk_inti'=> ' Stokist', 'identity_prk_inti'=> '01', 'prk_parent_id'=> 19],
                    [ 'id' => 10, 'desc_prk_inti'=> ' Jasa IT / EAM', 'identity_prk_inti'=> '02', 'prk_parent_id'=> 19],
                    [ 'id' => 11, 'desc_prk_inti'=> ' Sewa Pembangkit', 'identity_prk_inti'=> '03', 'prk_parent_id'=> 19],
                    [ 'id' => 12, 'desc_prk_inti'=> 'Lain - Lain', 'identity_prk_inti'=> '04', 'prk_parent_id'=> 19],
                    [ 'id' => 13, 'desc_prk_inti'=> 'Common', 'identity_prk_inti'=> '00', 'prk_parent_id'=> 20],
                    [ 'id' => 14, 'desc_prk_inti'=> 'PRK INTI BBM', 'identity_prk_inti'=> '00', 'prk_parent_id'=> 21],
                    [ 'id' => 15, 'desc_prk_inti'=> 'PRK INTI BBG', 'identity_prk_inti'=> '00', 'prk_parent_id'=> 22],
                    [ 'id' => 16, 'desc_prk_inti'=> 'PRK INTI BATUBARA', 'identity_prk_inti'=> '00', 'prk_parent_id'=> 23],
                    [ 'id' => 17, 'desc_prk_inti'=> 'PRK INTI PELUMAS', 'identity_prk_inti'=> '00', 'prk_parent_id'=> 24],
                    [ 'id' => 18, 'desc_prk_inti'=> 'PRK INTI KIMIA', 'identity_prk_inti'=> '00', 'prk_parent_id'=> 25],
                    [ 'id' => 19, 'desc_prk_inti'=> 'EP - Air', 'identity_prk_inti'=> '00', 'prk_parent_id'=> 26],
                    [ 'id' => 20, 'desc_prk_inti'=> 'Jasa O&M', 'identity_prk_inti'=> '01', 'prk_parent_id'=> 1],
                    [ 'id' => 21, 'desc_prk_inti'=> 'Material umum Kimia & Laboratorium', 'identity_prk_inti'=> '01', 'prk_parent_id'=> 2],
                    [ 'id' => 22, 'desc_prk_inti'=> 'Pemeliharaan dan kalibrasi peralatan laboratorium', 'identity_prk_inti'=> '02', 'prk_parent_id'=> 2],
                    [ 'id' => 23, 'desc_prk_inti'=> 'Material/jasa umum K3', 'identity_prk_inti'=> '01', 'prk_parent_id'=> 3],
                    [ 'id' => 24, 'desc_prk_inti'=> 'Sertifikasi peralatan', 'identity_prk_inti'=> '02', 'prk_parent_id'=> 3],
                    [ 'id' => 25, 'desc_prk_inti'=> 'Pengelolaan lingkungan & limbah', 'identity_prk_inti'=> '01', 'prk_parent_id'=> 4],
                    [ 'id' => 26, 'desc_prk_inti'=> 'Proper, penghijauan & 5S', 'identity_prk_inti'=> '02', 'prk_parent_id'=> 4],
                    [ 'id' => 27, 'desc_prk_inti'=> 'Jasa pendukung teknik', 'identity_prk_inti'=> '01', 'prk_parent_id'=> 5],
                    [ 'id' => 28, 'desc_prk_inti'=> 'Material Har Consumable', 'identity_prk_inti'=> '02', 'prk_parent_id'=> 5],
                    [ 'id' => 29, 'desc_prk_inti'=> 'Tools/material consumable/sparepart umum', 'identity_prk_inti'=> '01', 'prk_parent_id'=> 6],
                    [ 'id' => 30, 'desc_prk_inti'=> 'Assesment', 'identity_prk_inti'=> '02', 'prk_parent_id'=> 6],
                    [ 'id' => 31, 'desc_prk_inti'=> 'Jasa Pendukung Teknik', 'identity_prk_inti'=> '03', 'prk_parent_id'=> 6],
                    [ 'id' => 32, 'desc_prk_inti'=> 'Jasa pendukung teknik', 'identity_prk_inti'=> '01', 'prk_parent_id'=> 7],
                    [ 'id' => 33, 'desc_prk_inti'=> 'Pemeliharaan Corrective Umum', 'identity_prk_inti'=> '02', 'prk_parent_id'=> 7],
                    [ 'id' => 34, 'desc_prk_inti'=> 'Temuan OH', 'identity_prk_inti'=> '03', 'prk_parent_id'=> 7],
                    [ 'id' => 35, 'desc_prk_inti'=> 'Perbaikan sipil instalasi, sarana dan struktur', 'identity_prk_inti'=> '01', 'prk_parent_id'=> 9],
                    [ 'id' => 36, 'desc_prk_inti'=> 'Elektrikal dan instalasi', 'identity_prk_inti'=> '02', 'prk_parent_id'=> 9],
                    [ 'id' => 37, 'desc_prk_inti'=> 'Program retrofit/rekondisi equipment', 'identity_prk_inti'=> '03', 'prk_parent_id'=> 9],
                    [ 'id' => 38, 'desc_prk_inti'=> 'Penggantian/Upgrade spare part mekanik', 'identity_prk_inti'=> '04', 'prk_parent_id'=> 9],
                    [ 'id' => 39, 'desc_prk_inti'=> 'Sewa Kendaraan', 'identity_prk_inti'=> '01', 'prk_parent_id'=> 10],
                    [ 'id' => 40, 'desc_prk_inti'=> 'Peralatan & Perlengkapan Kantor', 'identity_prk_inti'=> '02', 'prk_parent_id'=> 10],
                    [ 'id' => 41, 'desc_prk_inti'=> 'Pemeliharaan Gedung / Mess / Rumah', 'identity_prk_inti'=> '03', 'prk_parent_id'=> 10],
                    [ 'id' => 42, 'desc_prk_inti'=> 'Cleaning Service', 'identity_prk_inti'=> '04', 'prk_parent_id'=> 10],
                    [ 'id' => 43, 'desc_prk_inti'=> 'Keamanan', 'identity_prk_inti'=> '05', 'prk_parent_id'=> 10],
                    [ 'id' => 44, 'desc_prk_inti'=> 'Lain - Lain', 'identity_prk_inti'=> '06', 'prk_parent_id'=> 10],
                    [ 'id' => 45, 'desc_prk_inti'=> 'Kompensasi Pegawai', 'identity_prk_inti'=> '01', 'prk_parent_id'=> 27],
                    [ 'id' => 46, 'desc_prk_inti'=> 'Manfaat Pegawai', 'identity_prk_inti'=> '02', 'prk_parent_id'=> 27],
                    [ 'id' => 47, 'desc_prk_inti'=> 'Diklat dan Lainnya', 'identity_prk_inti'=> '03', 'prk_parent_id'=> 27],
                    [ 'id' => 48, 'desc_prk_inti'=> 'Common', 'identity_prk_inti'=> '00', 'prk_parent_id'=> 28],
                    [ 'id' => 49, 'desc_prk_inti'=> 'Honorarium', 'identity_prk_inti'=> '01', 'prk_parent_id'=> 28],
                    [ 'id' => 50, 'desc_prk_inti'=> 'Asuransi', 'identity_prk_inti'=> '02', 'prk_parent_id'=> 28],
                    [ 'id' => 51, 'desc_prk_inti'=> 'Administrasi Umum', 'identity_prk_inti'=> '03', 'prk_parent_id'=> 28],
                    [ 'id' => 52, 'desc_prk_inti'=> 'Common', 'identity_prk_inti'=> '00', 'prk_parent_id'=> 29],
                    [ 'id' => 53, 'desc_prk_inti'=> ' Stokist', 'identity_prk_inti'=> '01', 'prk_parent_id'=> 30],
                    [ 'id' => 54, 'desc_prk_inti'=> ' Jasa IT / EAM', 'identity_prk_inti'=> '02', 'prk_parent_id'=> 30],
                    [ 'id' => 55, 'desc_prk_inti'=> ' Sewa Pembangkit', 'identity_prk_inti'=> '03', 'prk_parent_id'=> 30],
                    [ 'id' => 56, 'desc_prk_inti'=> 'Lain - Lain', 'identity_prk_inti'=> '04', 'prk_parent_id'=> 30],
                    [ 'id' => 57, 'desc_prk_inti'=> 'Common', 'identity_prk_inti'=> '00', 'prk_parent_id'=> 31],
                    [ 'id' => 58, 'desc_prk_inti'=> 'Common', 'identity_prk_inti'=> '00', 'prk_parent_id'=> 32],
                    [ 'id' => 59, 'desc_prk_inti'=> 'LKAI PLN', 'identity_prk_inti'=> '01', 'prk_parent_id'=> 32],
                    [ 'id' => 60, 'desc_prk_inti'=> 'LKAI PLN', 'identity_prk_inti'=> '02', 'prk_parent_id'=> 32],
                    [ 'id' => 61, 'desc_prk_inti'=> 'Common', 'identity_prk_inti'=> '00', 'prk_parent_id'=> 33],
                    [ 'id' => 62, 'desc_prk_inti'=> 'Honorarium', 'identity_prk_inti'=> '01', 'prk_parent_id'=> 36],
                    [ 'id' => 63, 'desc_prk_inti'=> 'Asuransi', 'identity_prk_inti'=> '02', 'prk_parent_id'=> 36],
                    [ 'id' => 64, 'desc_prk_inti'=> 'Administrasi Umum', 'identity_prk_inti'=> '03', 'prk_parent_id'=> 36],
        ];

        DB::table('prk_parent')->insert($parent);
        DB::table('prk_inti')->insert($inti);
    }
}
